/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import com.sun.opengl.util.Animator;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.media.opengl.GLCanvas;
import javax.media.opengl.GLEventListener;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JPanel;

/**
 *
 * @author vicOMG99
 */
public class menu extends javax.swing.JFrame {

    public boolean musicaoff = true;
    Clip sonidomen = null;
    int band,bndS=0;
    public static Clip clipFondo;
    
    public String Menu = "src/sonidos/MainMenu.wav";
    
    
    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);
       // if (band != 1) {
         //   sonidomenu("MainMenu");
        //}
       // System.out.println(band);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonPlay = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        so = new javax.swing.JButton();
        soff = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        botonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play.png"))); // NOI18N
        botonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPlayMouseClicked(evt);
            }
        });
        botonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlayActionPerformed(evt);
            }
        });
        jPanel1.add(botonPlay);
        botonPlay.setBounds(260, 140, 97, 73);

        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion.png"))); // NOI18N
        btnAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAyudaMouseClicked(evt);
            }
        });
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAyuda);
        btnAyuda.setBounds(10, 0, 40, 40);

        btnCreditos.setText("Créditos");
        btnCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreditosMouseClicked(evt);
            }
        });
        jPanel1.add(btnCreditos);
        btnCreditos.setBounds(70, 10, 100, 25);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("..Run Bot Run..");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 50, 270, 50);

        so.setText("Sonido ON");
        so.setToolTipText("");
        so.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soMouseClicked(evt);
            }
        });
        jPanel1.add(so);
        so.setBounds(130, 280, 120, 80);

        soff.setText("Sonido OFF");
        soff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soffMouseClicked(evt);
            }
        });
        jPanel1.add(soff);
        soff.setBounds(370, 280, 110, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-9, -4, 650, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPlayMouseClicked
    
        //this.setVisible(false);
        
       
    }//GEN-LAST:event_botonPlayMouseClicked

    private void botonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlayActionPerformed
        frmSeleccion2 per= new frmSeleccion2();
        per.setVisible(true);
        dispose();
        clipFondo.stop();
        
        
        //band = 1;
        //System.out.println(band);
    }//GEN-LAST:event_botonPlayActionPerformed

    private void btnAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAyudaMouseClicked
       this.setVisible(false);
       frmAyuda obj = new frmAyuda();
       obj.setVisible(true);
       //dispose();
    }//GEN-LAST:event_btnAyudaMouseClicked

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditosMouseClicked
        //this.setVisible(false);
       frmCreditos2 obj = new frmCreditos2();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnCreditosMouseClicked

    private void soffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soffMouseClicked
      /*  if (musicaoff == true) {
            sonidomen.stop();
            musicaoff = false;
        }*/
      
        clipFondo.stop();
    }//GEN-LAST:event_soffMouseClicked

    private void soMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soMouseClicked
       /* if (musicaoff == false) {
            sonidomenu("MainMenu");
            musicaoff = true;
        }*/
        
        if (bndS==0)
        {
            sonidoFondo("MainMenu");
        }
        clipFondo.start();
    }//GEN-LAST:event_soMouseClicked
    
    public void Sound(String a){
        if (sonidomen!=null) {
            sonidomen.stop();
        }
        sonidomenu(a);
    }
    
    public void sonidomenu(String ef) {
        try {
            sonidomen = AudioSystem.getClip();
            sonidomen.open(AudioSystem.getAudioInputStream(new File("src/sonidos/"+ef+".wav")));
            sonidomen.loop(1000);
        } catch (IOException e) {
            System.err.println(e.getMessage());
        } catch (LineUnavailableException e) {
            System.err.println(e.getMessage());
        } catch (UnsupportedAudioFileException e) {
            System.err.println(e.getMessage());
        }
    }
    
    
    public static synchronized void sonidoFondo(final String sonido)
    {
		new Thread(new Runnable()
		{
			// The wrapper thread is unnecessary, unless it blocks on the
			// Clip finishing; see comments.
			public void run()
			{
				File d = new File("src/sonidos/" + sonido + ".wav");
				try
				{
					clipFondo = AudioSystem.getClip();
					AudioInputStream inputStream = AudioSystem.getAudioInputStream(d);
					clipFondo.open(inputStream);
					clipFondo.start();
				} catch (Exception e)
				{
					System.err.println(e.getMessage());
				}
			}
		}).start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
                
            }
        });
    }
    
   
    
    public void setpane(JPanel a)
    {
        
              
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPlay;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCreditos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton so;
    private javax.swing.JButton soff;
    // End of variables declaration//GEN-END:variables
}
