/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import clases.Clase_Sonido;

/**
 *
 * @author carlo
 */
public class Niveles extends javax.swing.JFrame {

    public static int seleccionP = 0;
    Clase_Sonido son = new Clase_Sonido();

    public String Menu = "mainsong";

    public Niveles() {

        initComponents();
        son.sonidomenu(Menu);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        N1 = new javax.swing.JButton();
        N3 = new javax.swing.JButton();
        N2 = new javax.swing.JButton();
        gLCanvas1 = new javax.media.opengl.GLCanvas();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        N1.setText("Nivel 1");
        N1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N1MouseExited(evt);
            }
        });
        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });
        jPanel1.add(N1);
        N1.setBounds(400, 100, 66, 25);

        N3.setText("Nivel 3");
        N3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N3MouseExited(evt);
            }
        });
        N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N3ActionPerformed(evt);
            }
        });
        jPanel1.add(N3);
        N3.setBounds(400, 270, 66, 25);

        N2.setText("Nivel 2");
        N2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N2MouseExited(evt);
            }
        });
        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });
        jPanel1.add(N2);
        N2.setBounds(400, 180, 66, 25);
        jPanel1.add(gLCanvas1);
        gLCanvas1.setBounds(120, 130, 150, 130);

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 350, 61, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoM.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N3ActionPerformed
        seleccionP = 3;
        PlayGame(seleccionP);
    }//GEN-LAST:event_N3ActionPerformed

    private void N1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N1MouseEntered
        N2.setEnabled(false);
        N3.setEnabled(false);
    }//GEN-LAST:event_N1MouseEntered

    private void N2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N2MouseEntered
        N1.setEnabled(false);
        N3.setEnabled(false);
    }//GEN-LAST:event_N2MouseEntered

    private void N3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N3MouseEntered
        N1.setEnabled(false);
        N2.setEnabled(false);
    }//GEN-LAST:event_N3MouseEntered

    private void N1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N1MouseExited
        N2.setEnabled(true);
        N3.setEnabled(true);
    }//GEN-LAST:event_N1MouseExited

    private void N2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N2MouseExited
        N1.setEnabled(true);
        N3.setEnabled(true);
    }//GEN-LAST:event_N2MouseExited

    private void N3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N3MouseExited
        N1.setEnabled(true);
        N2.setEnabled(true);
    }//GEN-LAST:event_N3MouseExited

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
        seleccionP = 1;
        PlayGame(seleccionP);
    }//GEN-LAST:event_N1ActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
        seleccionP = 2;
        PlayGame(seleccionP);


    }//GEN-LAST:event_N2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       son.sonidoOff();
       frmSeleccion2 sel = new frmSeleccion2();
       sel.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void PlayGame(int var) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Niveles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton N1;
    private javax.swing.JButton N2;
    private javax.swing.JButton N3;
    private javax.media.opengl.GLCanvas gLCanvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
